apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRyZWcueGJldC5sYW4iOiB7fSwKCQkiZ2hjci5pbyI6IHsgImF1dGgiOiAiWVhKc2IzVjJhWFJoYkdrNloyaHdYekZCVWpGeWFYSmhNM1ZOU0hGQ2IzSlNlVkJNUVVaQll6ZG9WWFkyU3pSV04ybElOZz09IiB9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCgkicGx1Z2lucyI6IHsKCQkiLXgtY2xpLWhpbnRzIjogewoJCQkiZW5hYmxlZCI6ICJ0cnVlIgoJCX0sCgkJImRlYnVnIjogewoJCQkiaG9va3MiOiAiZXhlYyIKCQl9LAoJCSJzY291dCI6IHsKCQkJImhvb2tzIjogInB1bGwsYnVpbGR4IGJ1aWxkIgoJCX0KCX0sCgkiZmVhdHVyZXMiOiB7CgkJImhvb2tzIjogInRydWUiCgl9Cn0K
type: kubernetes.io/dockerconfigjson
